### ISSUE TITLE
`runj demo download` generates wrong URL for Arm hosts

### ISSUE THREAD

**Issue by samuelkarp** [samuelkarp/runj#15]
`runj demo download` detects the architecture for an Arm host as `aarch64` and attempts to construct a URL to download the rootfs.  However, the correct URL uses the architecture name `arm64`.

See: https://download.freebsd.org/ftp/releases/

**Comment by emaste** [comment]
I found `cmd := exec.CommandContext(ctx, "uname", "-p")` although it's in demo/version.go

**Comment by samuelkarp** [comment]
I'd be happy to take a PR fixing this if anyone is interested.  Otherwise it'll wait until I next have an Arm machine that I'm working on.
