### ISSUE TITLE
Integration with registries

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [samuelkarp/runj#2]
Hello,

First of all, thank you for this great project. OCI support on FreeBSD is something I was playing with recently. I managed to fix FreeBSD support in [umoci](https://github.com/opencontainers/umoci) and [skopeo](https://github.com/containers/skopeo). With these tools it's very easy to work with OCI images. 
Here is OCI image that contain FreeBSD base and was built on FreeBSD:
https://hub.docker.com/repository/docker/kwiat/freebsd

Here are snippets so that you can see how these tools work:
https://gitlab.com/runhyve/jailer/-/snippets

Cheers!

**Comment by mateuszkwiatkowski** [comment]
I figured that this stuff can also be handled with containerd so I don't think that interacting with registries is in scope of this project.
Having that said, I have successfully created a container with containerd:
```
# containerd &
# ctr i  pull docker.io/kwiat/freebsd:13.0-BETA4
docker.io/kwiat/freebsd:13.0-BETA4:                                               resolved       |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:ddc5c58e86491139db256f69ee7d6a888d4c70479b4b1ae2d53c06c24bb2664d: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:5fcdbc70fd1423c5d8aa6510776646df6ab301e3bc0867f9a93487633a534a28:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:34f029567538ca9635116074c5f16f094592a6d6e35b83a877ac046d0ff1b8cb:   done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 92.3s                                                                    total:  290.0  (3.1 MiB/s)
unpacking freebsd/amd64 sha256:ddc5c58e86491139db256f69ee7d6a888d4c70479b4b1ae2d53c06c24bb2664d...
done: 40.941850397s
# ctr c create  --runtime wtf.sbk.runj.v1 docker.io/kwiat/freebsd:13.0-BETA4 freebsd
# ctr task start freebsd
time="2021-03-18T14:51:29.167086007+01:00" level=info msg="starting signal loop" namespace=default path=/run/containerd/io.containerd.runtime.v2.task/default/freebsd pid=44256
time="2021-03-18T14:51:29.168067214+01:00" level=warning msg=CREATE req="&CreateTaskRequest{ID:freebsd,Bundle:/run/containerd/io.containerd.runtime.v2.task/default/freebsd,Rootfs:[]*Mount{&types.Mount{Type:nullfs,Source:/var/lib/containerd/io.containerd.snapshotter.v1.native/snapshots/3,Target:,Options:[rw],XXX_unrecognized:[],},},Terminal:false,Stdin:/run/containerd/fifo/860277668/freebsd-stdin,Stdout:/run/containerd/fifo/860277668/freebsd-stdout,Stderr:/run/containerd/fifo/860277668/freebsd-stderr,Checkpoint:,ParentCheckpoint:,Options:nil,XXX_unrecognized:[],}" runtime=wtf.sbk.runj.v1
[CUT]
# ctr task list
TASK       PID      STATUS
freebsd    68076    RUNNING
```

I'll close this issue and continue playing with runj. Once again: thanks for this project!

**Comment by samuelkarp** [comment]
Hi @mateuszkwiatkowski, I'm glad you got it working!  runj has a [built-in utility](https://github.com/samuelkarp/runj#oci-image) for generating FreeBSD base images that you can use as well.  I haven't had the chance to push this to a container registry yet, but it should theoretically work fine :sweat_smile:.

**Comment by samuelkarp** [comment]
Hey @mateuszkwiatkowski, I've also uploaded a base image to the [Amazon ECR public gallery](https://gallery.ecr.aws/samuelkarp/freebsd).  You can pull it with the `ctr` tool like this:

```
$ sudo ctr image pull public.ecr.aws/samuelkarp/freebsd:12.1-RELEASE
```

**Comment by mateuszkwiatkowski** [comment]
Hi @samuelkarp, Thanks for images in public gallery. I also pushed base images to Docker Hub: https://hub.docker.com/repository/docker/kwiat/freebsd
And started discussion about official images provided by the project: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254645

**Comment by samuelkarp** [comment]
@mateuszkwiatkowski Awesome! I've joined the bugzilla and started to comment there.
