### ISSUE TITLE
Cirrus CI uses outdated FreeBSD release

### ISSUE THREAD

**Issue by hdbhm** [samuelkarp/runj#44]
The current Cirrus CI configuration uses FreeBSD 13.0, which reached its end of life August 31, 2022. This causes pipeline failures, because the integration tests try to download an image that does not longer exist on the official download servers.

I would be willing to provide a PR, changing the image to freebsd-13.2. Apart from updating `image_family` in `.cirrus.yml`, is there anything I should be aware of that would have to be done as well?

**Comment by emaste** [comment]
Updating image_family should be all that's needed.
