### ISSUE TITLE
runj demo invalid character in URL

### ISSUE THREAD

**Issue by gizahNL** [samuelkarp/runj#5]
When trying the demo command as specified in the README.md I get the following error:

Error: parse "http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/13.0-RELEASE\n/base.txz": net/url: invalid control character in URL

```
root@mergusserator:~/runj # ./bin/runj demo download --output rootfs.txz
Found arch:  amd64
Found version:  13.0-RELEASE

Downloading image for amd64 13.0-RELEASE
 into rootfs.txz
Error: parse "http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/13.0-RELEASE\n/base.txz": net/url: invalid control character in URL
Usage:
  runj demo download [flags]

Flags:
  -a, --architecture string   CPU architecture, like amd64
  -h, --help                  help for download
  -o, --output string         Output filename (default "rootfs.txz")
  -v, --version string        FreeBSD version, like 12-RELEASE

```

**Comment by gizahNL** [comment]
```
diff --git a/demo/version.go b/demo/version.go
index a061096..af4afc3 100644
--- a/demo/version.go
+++ b/demo/version.go
@@ -12,7 +12,7 @@ func FreeBSDVersion(ctx context.Context) (string, error) {
        if err != nil {
                return "", err
        }
-       vers := strings.Split(string(version), "-")
+       vers := strings.Split(strings.Trim(string(version), "\n"), "-")
        if len(vers) < 2 {
                return vers[0], nil
        }
```

**Comment by lwhsu** [comment]
Just seeing this and want to note that there is https://download.freebsd.org :)

**Comment by samuelkarp** [comment]
Thanks for the bug report.  Can you try this and see if it works around the issue you're seeing?

```
./bin/runj demo download --output rootfs.txz --version 13.0-RELEASE
```

**Comment by gizahNL** [comment]
> Thanks for the bug report. Can you try this and see if it works around the issue you're seeing?
> 
> ```
> ./bin/runj demo download --output rootfs.txz --version 13.0-RELEASE
> ```

Yes that works

**Comment by samuelkarp** [comment]
> Just seeing this and want to note that there is download.freebsd.org :)

@lwhsu Thanks for the pointer, seems like I should switch.

@gizahNL Thanks for the patch.

In spite of the [contribution policy](https://github.com/samuelkarp/runj/blob/main/CONTRIBUTING.md), if either or both of you are interested in opening a pull request to fix the respective problems you've identified and are willing to license it [under the same terms of this repository](https://github.com/samuelkarp/runj/blob/main/LICENSE), I'd be happy to merge those small, targeted fixes.

**Comment by matias-pizarro** [comment]
FYI @lwhsu's suggestion and @gizahNL 's patch work beautifully together.
Happy to open a PR but that's not my code :D

On a more general note, I love what you are doing

**Comment by matias-pizarro** [comment]
@samuelkarp FYI https://github.com/samuelkarp/runj/compare/main...matias-pizarro:develop

**Comment by samuelkarp** [comment]
@matias-pizarro While I appreciate the enthusiasm, please keep in mind the [contribution policy](https://github.com/samuelkarp/runj/blob/main/CONTRIBUTING.md).  This file will change when I'm ready to accept more contributions.

**Comment by matias-pizarro** [comment]
Fully understood, that's why I have not created a PR, but still gave you visibility on the possible patch.

**Comment by samuelkarp** [comment]
@gizahNL Thanks for the bug report.  I've pushed a new commit which fixes this and have added a unit test to hopefully catch errors like this again.  I've credited you as the co-author in the commit.

**Comment by samuelkarp** [comment]
@lwhsu Thanks for the suggestion to use https://download.freebsd.org/; this has been changed in the latest commit.
