### ISSUE TITLE
missing module from vendor ?

### ISSUE THREAD

**Issue by dch** [samuelkarp/runj#55]
I'm updating the [sysutils/runj port](https://cgit.freebsd.org/ports/tree/sysutils/runj) to the 20231221 snapshot, but getting a build error. I don't know enough go to understand what's missing, and how to fix this - any suggestions?

```
# excerpt from full build log https://pkg.skunkwerks.at/poudriere/data/current_x64-default/2024-01-04_16h17m38s/logs/errors/runj-g20231221.log
...

===>  Building runj-entrypoint from ./cmd/runj-entrypoint
github.com/containerd/console
go.sbk.wtf/runj/cmd/runj-entrypoint
===>  Building containerd-shim-runj-v1 from ./cmd/containerd-shim-runj-v1
go: finding module for package google.golang.org/genproto/googleapis/rpc/status
vendor/github.com/containerd/ttrpc/types.go:22:2: cannot query module due to -mod=vendor
*** Error code 1
```

Normally we'd use [go:modules](https://docs.freebsd.org/en/books/porters-handbook/book/#using-go) to build these but this isn't possible until there's a tagged version I think of runj.

Here's my current patched port:

https://paste.sr.ht/~dch/495ccdbef07186a00fd686bdb18e273819010ab3

**Comment by tianon** [comment]
(disclaimer: I'm not a maintainer here :sweat_smile:)

There isn't a `vendor` directory in this project (https://github.com/samuelkarp/runj/commits/main/vendor), so I'm not sure where `-mod=vendor` is coming from (`GOFLAGS`?) but that's probably the problem. :eyes:

**Comment by samuelkarp** [comment]
I can't reproduce this just with vendoring, though I did test after updating the go.mod to use post-1.16 requirements: https://github.com/samuelkarp/runj/pull/56.

Can you test with that PR and see if it fixes the issue?

**Comment by samuelkarp** [comment]
I've also just published [v0.1.0](https://github.com/samuelkarp/runj/releases/tag/v0.1.0), which was a long time coming.

For the port, you may want to override the contents of the `REV_OVERRIDE` file with `6f91a7f2f94f35a22c790c55d658dd27bdcb5748`.

**Comment by dch** [comment]
thanks the tag makes this much simpler, build just works now. What’s the significance of REV_OVERRIDE?

**Comment by dch** [comment]
Aah found it in here already - thanks https://github.com/samuelkarp/runj/commit/7aa422da05c7cd4fd36cbfaa0c0dedf31c6a30a2

**Comment by dch** [comment]
FYI the updated port has been committed. Thanks @samuelkarp for the tag!
