### ISSUE TITLE
Containers started via ctr remain as active snapshots.

### ISSUE THREAD

**Issue by gizahNL** [samuelkarp/runj#6]
Not sure if this is just wrong usage of CTR, but I notice containers I run do not seem to get cleaned up properly, they remain in ctr snapshot list and I'm prohibited from starting a new one with the same name. 

I "think" I see the same behavior with Docker (https://github.com/gizahNL/moby/tree/freebsd-port), I see docker allocating but never freeing up any zfs datasets after running a container

**Comment by tianon** [comment]
Just to be sure, are you using `--rm` on your `ctr run` invocation? :sweat_smile:

**Comment by gizahNL** [comment]
> Just to be sure, are you using `--rm` on your `ctr run` invocation? 😅

No... I'm an idiot! Ty....

**Comment by samuelkarp** [comment]
Thanks @tianon for the help here!
